description: >
  Ubuntu-based machine executor VM for Docker builds and deployments.
  Provides Docker engine and necessary tools for container operations.
  https://circleci.com/docs/2.0/executor-types/#using-machine
parameters:
  image:
    type: string
    default: ubuntu-2204:current
    description: >
      Ubuntu machine image to use:
      https://circleci.com/docs/2.0/configuration-reference/#available-linux-machine-images
  docker_layer_caching:
    type: boolean
    default: false
    description: >
      Enable Docker layer caching for faster builds when using Docker commands.
  resource_class:
    type: string
    default: small
    description: >
      Resource class for the machine executor (small, medium, large, xlarge, 2xlarge).

machine:
  image: <<parameters.image>>
  docker_layer_caching: <<parameters.docker_layer_caching>>
resource_class: <<parameters.resource_class>>
