description: >
  Docker executor with Docker-in-Docker support for building and pushing container images.
  Compatible with CircleCI's free plan and provides all necessary tools for container operations.
  https://circleci.com/docs/2.0/executor-types/#using-docker
parameters:
  image:
    type: string
    default: cimg/base:2024.01
    description: >
      Docker image to use for the executor.
      Recommended: cimg/base:2024.01 or cimg/node:18.19
  docker_layer_caching:
    type: boolean
    default: false
    description: >
      Enable Docker layer caching for faster builds when using Docker commands.
  resource_class:
    type: string
    default: small
    description: >
      Resource class for the Docker executor (small, medium, large, xlarge, 2xlarge).

docker:
  - image: <<parameters.image>>
    environment:
      DOCKER_BUILDKIT: 1
      COMPOSE_DOCKER_CLI_BUILD: 1
